### ISSUE TITLE
Example of Configuration file

### ISSUE THREAD

**Issue by manuGil** [sedtrails/sedtrails#146]
@jreyns  Do we have an example of a valid `sedtrails.yaml` configuration file in the repo? If not, could you add one please.

**Comment by manuGil** [comment]
This can be generated from the current code.

**Comment by manuGil** [comment]
@jreyns I generated a YAML file using the `YAMLConfigValidator` class. Specifically the ` export_schema_to_yaml()`. This produced a file that looks like this

```yaml
$schema: http://json-schema.org/draft-07/schema#
title: Configuration Schema
type: object
properties:
  General:
    type: object
    properties:
      preprocess:
        type: integer
        default: 1
        description: 1 = pre-process, 0 = use existing files with default names
      computePathways:
        type: integer
        default: 1
        description: (re)run everything = 1, load existing pathways = 0;
      inputModelType:
        type: string
        default: '''dfm'''
        description: '''dfm'' = D-Flow FM, ''d3d4'' = Delft3D-4, ''xbeach'' = xbeach,
          ''aeolis'' = aeolis, etc...'
      supportedModelTypes:
        type: string
        default: '{''dfm'',''d3d4''}'
      nRuns:
        type: integer
```
My understanding is that the file contains a description of the schema in YAML, but not an example of a valid configuration file. Do we have code that will do the latter?
