### ISSUE TITLE
Validation of sedtrails.yaml fails due to type error

### ISSUE THREAD

**Issue by manuGil** [sedtrails/sedtrails#177]
The current schema for the configuration file of a simulation defines certain elements as strings, but their default values generated by our YAML writer aren't strings.  

For example:

```json
"connSetup_perimeterPolFile": {
              "type": "string",
              "default": "[]",
              "description": ".pol file containing perimeter polygon to manually limit extents"
            },
            "connSetup_islandsPolFile": {
              "type": "string",
              "default": "[]",
              "description": ".pol file containing island polygons"
            },
```

The errors might be caused by a discrepancy between the YAML written by our implementation and the schema. 
The error happens when passing a configuration.yaml that defines simulation parameters such as (notice that values with `[]` are expected to be strings, but they are treated as arrays by the validator):

```yaml
Connectivity auto-define:
    connSetup_useAlphaShape: 0
    connSetup_holeThreshold: 0.0
    connSetup_bufferDist: 0.0
    connSetup_cluster_k: 5.0
    connSetup_cluster_iter: 40.0
    connSetup_showCheckPlots: 0
    connSetup_saveCheckPlots: 0
    connSetup_perimeterPolFile:  [] 
    connSetup_islandsPolFile:  [] 
    connectivity_PolFile:  [] 
    plot_mgmtPolygons_PolFile:  [] 
    connectivity_mergePolygonMode: 1
    connectivity_polygonMerging_distThreshold: 1.0
    connectivity_polygonCreator_showCheckPlots: 0
```
If strings are enough for this case, then a better choice for a default above would be a empty sting.
@jreyns  I can work on a fix for this. But I would like to know what a **.pol** file is and if the value expected here is a path to a file or multiple files, or if we should change the type to an array.
